version: 2
updates:
  - package-ecosystem: "npm"      
    directory: "/linkhub-app"    
    schedule:
      interval: "daily"           
    open-pull-requests-limit: 10   
    assignees:
     - "Saliim17"
    auto-merge: true
    
  - package-ecosystem: "npm"     
    directory: "/linkhub-api"     
    schedule:
      interval: "daily"        
    open-pull-requests-limit: 10
    assignees:
     - "Saliim17"
    auto-merge: true